### ISSUE TITLE
`--build` doesn't seem to work

### ISSUE THREAD

**Issue by ghost** [trevershick/djs#10]
➜  Desktop djs --project ProjectName --branch release-2.4.0 --build 4
Reading ~/.djsrc...done
Reading .djsrc...done
Determine current git branch...done
Determine the current project...done
  Resolving the download URL
ERROR 404 Not Found - https://jenkins.local/job/CompanyName/job/ProjectName/job/release-2.4.0/4/api/xml?xpath=/*/artifact[fileName=%22d.xml%22]/relativePath&wrapper=x

**Comment by trevershick** [comment]
Do you have a 'd.xml' in that project/solution?  It has to be able to locate the file in jenkins so i fthere's no file named d.xml in the artifacts it won't work.

**Comment by trevershick** [comment]
'latest' definitely doesn't work when used with --build

**Comment by trevershick** [comment]
'latest' is fixed in 0.4.0. i'm not sure if 0.4.0 will fix your issues but hopefully it will.
